FROM wilkesystems/steamcmd:jessie-slim

RUN steamcmd +login anonymous \
    +force_install_dir /home/hl2dm/ \
    +app_update 232370 validate \
    +app_update 232370 validate \
    +quit

WORKDIR /home/hl2dm/